// Sweet Haven Bakery — Product Data
const PRODUCTS = [
  {
    id: 1,
    name: "Chocolate Truffle Cake",
    category: "Cakes",
    price: 799,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80",
    description: "Decadent layers of dark chocolate sponge filled with velvety truffle ganache, finished with a mirror-glaze.",
    rating: 4.9,
    isEggless: false,
    isVegan: false,
    weight: "500g",
    servings: "6–8",
    ingredients: ["Dark chocolate", "Fresh cream", "Flour", "Eggs", "Butter", "Cocoa powder"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["bestseller", "new"]
  },
  {
    id: 2,
    name: "Red Velvet Cake",
    category: "Cakes",
    price: 749,
    image: "https://images.unsplash.com/photo-1586788224331-947f68671cf1?w=600&q=80",
    description: "Classic red velvet with cream cheese frosting — moist, tangy, and utterly irresistible.",
    rating: 4.8,
    isEggless: false,
    isVegan: false,
    weight: "500g",
    servings: "6–8",
    ingredients: ["Red food colour", "Buttermilk", "Cream cheese", "Butter", "Cocoa"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["bestseller"]
  },
  {
    id: 3,
    name: "Mango Passionfruit Cake",
    category: "Cakes",
    price: 849,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&q=80",
    description: "Light vanilla sponge layered with fresh mango compote and whipped passionfruit cream. A Mumbai summer special.",
    rating: 4.7,
    isEggless: false,
    isVegan: false,
    weight: "500g",
    servings: "6–8",
    ingredients: ["Mango pulp", "Passionfruit", "Fresh cream", "Vanilla sponge"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["seasonal"]
  },
  {
    id: 4,
    name: "Eggless Black Forest",
    category: "Cakes",
    price: 699,
    image: "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=600&q=80",
    description: "Classic Black Forest reimagined without eggs — cherries, cream and moist chocolate sponge.",
    rating: 4.8,
    isEggless: true,
    isVegan: false,
    weight: "500g",
    servings: "6–8",
    ingredients: ["Cocoa", "Cherries", "Whipped cream", "Maraschino"],
    allergens: "Gluten, Dairy",
    tags: ["eggless"]
  },
  {
    id: 5,
    name: "Vegan Lemon Blueberry Cake",
    category: "Cakes",
    price: 899,
    image: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=600&q=80",
    description: "Bright citrus sponge studded with fresh blueberries, frosted with cashew cream. 100% plant-based.",
    rating: 4.6,
    isEggless: true,
    isVegan: true,
    weight: "500g",
    servings: "6–8",
    ingredients: ["Almond milk", "Lemon zest", "Blueberries", "Cashew cream", "Coconut oil"],
    allergens: "Gluten, Tree nuts",
    tags: ["vegan", "eggless"]
  },
  {
    id: 6,
    name: "Butter Croissant",
    category: "Pastries",
    price: 89,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
    description: "Flaky, laminated croissant made with 84% fat butter — 72 hours of love in every bite.",
    rating: 4.9,
    isEggless: false,
    isVegan: false,
    weight: "80g",
    servings: "1",
    ingredients: ["Flour", "Butter", "Milk", "Yeast", "Sugar"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["bestseller", "daily-fresh"]
  },
  {
    id: 7,
    name: "Almond Pain au Chocolat",
    category: "Pastries",
    price: 120,
    image: "https://images.unsplash.com/photo-1571167530149-c1105da4c2c0?w=600&q=80",
    description: "Croissant dough folded around Belgian dark chocolate, topped with toasted almond flakes.",
    rating: 4.8,
    isEggless: false,
    isVegan: false,
    weight: "95g",
    servings: "1",
    ingredients: ["Croissant dough", "Dark chocolate", "Almonds", "Frangipane"],
    allergens: "Gluten, Dairy, Eggs, Tree nuts",
    tags: []
  },
  {
    id: 8,
    name: "Blueberry Muffin",
    category: "Pastries",
    price: 79,
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=600&q=80",
    description: "Bakery-style muffin bursting with fresh blueberries, crunchy sugar crust on top.",
    rating: 4.7,
    isEggless: false,
    isVegan: false,
    weight: "120g",
    servings: "1",
    ingredients: ["Blueberries", "Flour", "Butter", "Buttermilk", "Sugar"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["daily-fresh"]
  },
  {
    id: 9,
    name: "Cinnamon Danish",
    category: "Pastries",
    price: 99,
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80",
    description: "Spiralled Danish pastry with cinnamon sugar filling, drizzled with vanilla glaze.",
    rating: 4.6,
    isEggless: false,
    isVegan: false,
    weight: "100g",
    servings: "1",
    ingredients: ["Danish dough", "Cinnamon", "Brown sugar", "Vanilla glaze"],
    allergens: "Gluten, Dairy, Eggs",
    tags: []
  },
  {
    id: 10,
    name: "Sourdough Boule",
    category: "Breads",
    price: 280,
    image: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=600&q=80",
    description: "Wild-fermented sourdough with a crackling crust and open crumb. Baked fresh every morning.",
    rating: 4.9,
    isEggless: true,
    isVegan: true,
    weight: "700g",
    servings: "8–10",
    ingredients: ["Organic flour", "Water", "Sea salt", "Wild yeast starter"],
    allergens: "Gluten",
    tags: ["vegan", "eggless", "bestseller"]
  },
  {
    id: 11,
    name: "Mumbai Pav (6 pack)",
    category: "Breads",
    price: 60,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    description: "Soft, pillowy pav — the perfect partner for bhaji, keema or butter. Made fresh twice daily.",
    rating: 4.8,
    isEggless: false,
    isVegan: false,
    weight: "300g",
    servings: "6",
    ingredients: ["Maida", "Milk", "Butter", "Sugar", "Yeast"],
    allergens: "Gluten, Dairy",
    tags: ["daily-fresh", "bestseller"]
  },
  {
    id: 12,
    name: "Multigrain Loaf",
    category: "Breads",
    price: 220,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    description: "Seeded multigrain loaf with oats, flaxseeds, sunflower seeds and whole wheat.",
    rating: 4.7,
    isEggless: true,
    isVegan: true,
    weight: "600g",
    servings: "8",
    ingredients: ["Whole wheat", "Oats", "Flaxseeds", "Sunflower seeds", "Sesame"],
    allergens: "Gluten, Seeds",
    tags: ["vegan", "eggless"]
  },
  {
    id: 13,
    name: "Double Chocolate Brownie",
    category: "Cookies",
    price: 65,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80",
    description: "Fudgy, crinkle-top brownie packed with both cocoa and dark chocolate chips.",
    rating: 4.9,
    isEggless: false,
    isVegan: false,
    weight: "90g",
    servings: "1",
    ingredients: ["Dark chocolate", "Cocoa powder", "Butter", "Eggs", "Sugar"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["bestseller"]
  },
  {
    id: 14,
    name: "Choco Chip Cookies (6 pack)",
    category: "Cookies",
    price: 180,
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80",
    description: "Classic NY-style thick cookies — crisp edges, gooey centre, puddles of melted chocolate.",
    rating: 4.8,
    isEggless: false,
    isVegan: false,
    weight: "300g",
    servings: "6",
    ingredients: ["Butter", "Brown sugar", "Chocolate chips", "Flour", "Vanilla"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["bestseller"]
  },
  {
    id: 15,
    name: "Nankhatai (Box of 12)",
    category: "Cookies",
    price: 220,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80",
    description: "Traditional Indian shortbread cookies flavoured with cardamom and topped with pistachios.",
    rating: 4.8,
    isEggless: true,
    isVegan: false,
    weight: "240g",
    servings: "12",
    ingredients: ["Maida", "Ghee", "Sugar", "Cardamom", "Pistachios"],
    allergens: "Gluten, Dairy, Tree nuts",
    tags: ["eggless", "indian"]
  },
  {
    id: 16,
    name: "Gulab Jamun (Box of 6)",
    category: "Indian Mithai",
    price: 160,
    image: "https://images.unsplash.com/photo-1601303516534-bf4acf270d5e?w=600&q=80",
    description: "Soft khoya dumplings soaked in rose-cardamom sugar syrup. Served warm.",
    rating: 4.9,
    isEggless: true,
    isVegan: false,
    weight: "300g",
    servings: "6",
    ingredients: ["Khoya", "Maida", "Sugar syrup", "Cardamom", "Rose water"],
    allergens: "Gluten, Dairy",
    tags: ["eggless", "indian", "bestseller"]
  },
  {
    id: 17,
    name: "Rasgulla (Box of 6)",
    category: "Indian Mithai",
    price: 140,
    image: "https://images.unsplash.com/photo-1628876024186-7ac9d81b1e4d?w=600&q=80",
    description: "Pillowy soft chenna balls in light sugar syrup — the Bengal classic, made fresh daily.",
    rating: 4.7,
    isEggless: true,
    isVegan: false,
    weight: "300g",
    servings: "6",
    ingredients: ["Chenna", "Sugar", "Water", "Rose water"],
    allergens: "Dairy",
    tags: ["eggless", "indian"]
  },
  {
    id: 18,
    name: "Motichoor Laddoo (Box of 6)",
    category: "Indian Mithai",
    price: 180,
    image: "https://images.unsplash.com/photo-1582396618652-d30ddf7041fd?w=600&q=80",
    description: "Delicate saffron-infused motichoor laddoos garnished with pistachios. Perfect for celebrations.",
    rating: 4.8,
    isEggless: true,
    isVegan: false,
    weight: "240g",
    servings: "6",
    ingredients: ["Besan", "Ghee", "Sugar syrup", "Saffron", "Pistachios"],
    allergens: "Gluten, Dairy, Tree nuts",
    tags: ["eggless", "indian", "bestseller"]
  },
  {
    id: 19,
    name: "Kaju Katli (250g)",
    category: "Indian Mithai",
    price: 350,
    image: "https://images.unsplash.com/photo-1559703248-dcaaec9fab78?w=600&q=80",
    description: "Silky smooth cashew fudge layered with silver vark — a festive favourite.",
    rating: 4.9,
    isEggless: true,
    isVegan: false,
    weight: "250g",
    servings: "10",
    ingredients: ["Cashews", "Sugar", "Cardamom", "Silver vark"],
    allergens: "Tree nuts, Dairy",
    tags: ["eggless", "indian", "bestseller"]
  },
  {
    id: 20,
    name: "Besan Barfi (250g)",
    category: "Indian Mithai",
    price: 280,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&q=80",
    description: "Slow-roasted besan barfi with ghee and cardamom — deeply flavourful traditional sweet.",
    rating: 4.7,
    isEggless: true,
    isVegan: false,
    weight: "250g",
    servings: "10",
    ingredients: ["Besan", "Ghee", "Sugar", "Cardamom", "Cashews"],
    allergens: "Gluten, Dairy, Tree nuts",
    tags: ["eggless", "indian"]
  },
  {
    id: 21,
    name: "Custom Birthday Cake",
    category: "Cakes",
    price: 1499,
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600&q=80",
    description: "Fully customisable birthday cake — choose your flavour, frosting, size, and we'll write any message.",
    rating: 5.0,
    isEggless: false,
    isVegan: false,
    weight: "1kg",
    servings: "12–15",
    ingredients: ["Customised to your choice"],
    allergens: "Varies by choice",
    tags: ["custom", "bestseller"]
  },
  {
    id: 22,
    name: "Vegan Banana Bread",
    category: "Breads",
    price: 240,
    image: "https://images.unsplash.com/photo-1582062577665-a97e5f249555?w=600&q=80",
    description: "Moist, deeply caramelised banana bread with walnuts and dark chocolate chunks. Fully vegan.",
    rating: 4.7,
    isEggless: true,
    isVegan: true,
    weight: "400g",
    servings: "6",
    ingredients: ["Ripe bananas", "Oat flour", "Coconut oil", "Walnuts", "Dark chocolate"],
    allergens: "Gluten, Tree nuts",
    tags: ["vegan", "eggless"]
  },
  {
    id: 23,
    name: "Gluten-Free Almond Cake",
    category: "Cakes",
    price: 950,
    image: "https://images.unsplash.com/photo-1519327232521-1ea2c736d34d?w=600&q=80",
    description: "Dense, moist flourless almond cake with orange zest and a dusting of icing sugar.",
    rating: 4.6,
    isEggless: false,
    isVegan: false,
    weight: "500g",
    servings: "8",
    ingredients: ["Almond flour", "Eggs", "Butter", "Orange zest", "Sugar"],
    allergens: "Dairy, Eggs, Tree nuts",
    tags: ["gluten-free"]
  },
  {
    id: 24,
    name: "Strawberry Tart",
    category: "Pastries",
    price: 220,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
    description: "Crisp pâte sablée shell filled with vanilla pastry cream and crowned with fresh strawberries.",
    rating: 4.8,
    isEggless: false,
    isVegan: false,
    weight: "200g",
    servings: "2–3",
    ingredients: ["Tart shell", "Pastry cream", "Fresh strawberries", "Nappage glaze"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["seasonal"]
  },
  {
    id: 25,
    name: "Chai Spice Cookies (6 pack)",
    category: "Cookies",
    price: 200,
    image: "https://images.unsplash.com/photo-1548369937-47519962c11a?w=600&q=80",
    description: "Buttery shortbread infused with cardamom, ginger, cinnamon and cloves — a cup of chai in cookie form.",
    rating: 4.8,
    isEggless: false,
    isVegan: false,
    weight: "200g",
    servings: "6",
    ingredients: ["Butter", "Flour", "Cardamom", "Ginger", "Cinnamon", "Cloves"],
    allergens: "Gluten, Dairy, Eggs",
    tags: ["indian"]
  },
  {
    id: 26,
    name: "Opera Cake",
    category: "Cakes",
    price: 1199,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80",
    description: "Classic French Opera cake — almond joconde, coffee buttercream, and dark chocolate ganache in precise layers.",
    rating: 4.9,
    isEggless: false,
    isVegan: false,
    weight: "500g",
    servings: "8",
    ingredients: ["Almond joconde", "Coffee syrup", "Coffee buttercream", "Dark ganache"],
    allergens: "Gluten, Dairy, Eggs, Tree nuts",
    tags: ["premium", "bestseller"]
  }
];

const CATEGORIES = [
  { name: "Cakes",          icon: "🎂", image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&q=75", count: 7  },
  { name: "Pastries",       icon: "🥐", image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&q=75", count: 5  },
  { name: "Breads",         icon: "🍞", image: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=400&q=75", count: 4  },
  { name: "Cookies",        icon: "🍪", image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&q=75", count: 4  },
  { name: "Indian Mithai",  icon: "🪔", image: "https://images.unsplash.com/photo-1601303516534-bf4acf270d5e?w=400&q=75", count: 5  },
  { name: "Eggless/Vegan",  icon: "🌱", image: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=400&q=75", count: 8  },
];

const TESTIMONIALS = [
  { name: "Priya Sharma", role: "Regular Customer", quote: "Sweet Haven is my go-to for every celebration. The Chocolate Truffle Cake is absolutely divine — my family demands it for every birthday!", avatar: "https://i.pravatar.cc/150?img=47", stars: 5 },
  { name: "Rohan Mehta",  role: "Food Blogger", quote: "As a food critic, I rarely gush — but the butter croissants here rival anything I've had in Paris. Flaky, buttery perfection.", avatar: "https://i.pravatar.cc/150?img=12", stars: 5 },
  { name: "Ananya Iyer",  role: "Wedding Planner", quote: "Ordered a custom three-tier cake for my client's wedding. Not only was it stunning, it was the first cake to disappear at the reception!", avatar: "https://i.pravatar.cc/150?img=32", stars: 5 },
  { name: "Vikram Nair",  role: "Office Manager", quote: "We order the Kaju Katli and Motichoor Laddoos for all office celebrations. The quality is consistent, the packaging beautiful.", avatar: "https://i.pravatar.cc/150?img=3",  stars: 5 },
  { name: "Meera Pillai", role: "Home Baker", quote: "Their sourdough boule inspired me to start baking myself. The depth of flavour from a real ferment — unmatched in Mumbai.", avatar: "https://i.pravatar.cc/150?img=23", stars: 5 },
];

const TEAM = [
  { name: "Kavya Nair",    role: "Head Pastry Chef",  bio: "15 years of fine pastry training, Le Cordon Bleu Paris alumna.", avatar: "https://i.pravatar.cc/150?img=44" },
  { name: "Arjun Kapoor",  role: "Head Baker",         bio: "Sourdough obsessive. Has been nurturing our starter for 6 years.", avatar: "https://i.pravatar.cc/150?img=7" },
  { name: "Sneha Joshi",   role: "Indian Sweets Chef", bio: "Fourth-generation mithai maker from Kolkata.", avatar: "https://i.pravatar.cc/150?img=25" },
  { name: "Riya Desai",    role: "Cake Designer",      bio: "Trained at École Ferrandi Paris. Specialises in sculpted cakes.", avatar: "https://i.pravatar.cc/150?img=35" },
];
